---
- name: create vm 
  hosts: localhost
  become: false
  gather_facts: false
  vars_files:
    - vars.yml
  tasks:
    - name: create folder
      community.vmware.vcenter_folder:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        datacenter: "{{ vcenter_datacenter }}"
        folder_name: "{{ vcenter_destination_folder }}"
        folder_type: "{{ vcenter_destination_folder_type }}"
        state: "{{ vcenter_destination_folder_state }}"
    - name: Clone the template
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        name: "{{ vm_name }}"
        template: "{{ vm_template }}"
        datacenter: "{{ vcenter_datacenter }}"
        folder: "{{ vcenter_destination_folder }}"
        state: "{{ vm_state }}"
        cluster: "{{ vcenter_cluster }}"
        wait_for_ip_address: "{{ wait_for_ip }}"
