---
- name: create vm 
  hosts: localhost
  become: false
  gather_facts: false
  
  vars_files:
    - vars.yml
  
  tasks:
  - name: Clone the template
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: "{{ vcenter_validate_certs }}"
      name: testvm_2
      template: "{{ vm_template }}"
      datacenter: "{{ vcenter_datacenter }}"
      folder: "{{ vcenter_destination_folder }}"
      state: "{{ vm_state }}"
      cluster: "{{ vcenter_cluster }}"
      wait_for_ip_address: yes
