---
- name: Apply Local DNS Entries
  hosts: all
  become: true
  tasks:
    - name: TASK | Copy DNS entires to DNS Servers
      template: src=template-dns.list dest=/etc/pihole/custom.list force=yes
#    - name: TASK | Restart dnsmasq
 #     service:
  #      name: dnsmasq
   #     state: restarted

