---
- name: Play to Shutdown Windows
  hosts: windows
  become: false
  gather_facts: false
  tasks:
  - name: Test Connection to Windows Server
    ansible.windows.win_ping:
  # - name: Shutdown Windows PC
    # ansible.windows.win_command:
      # cmd: shutdown -s -f -t 0
